import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cart Products | Tech Gadget",
  description: "Generated by create next app",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
