import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";

import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home | Tech Gadget",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <div className='flex flex-col min-h-screen bg-white dark:bg-slate-900 transition-colors duration-200'>
            {children}
          </div>
          <Footer />
        </ThemeProvider>
        <Toaster
          position="top-right"
          richColors
          closeButton
          duration={2000}
          expand
          visibleToasts={5}
        />
      </body>
    </html>
  );
}
