import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Checkout | Tech Gadget",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
